language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# django 1.4.0 doesn't have six. Only newest version have this module.
env:
  - DJANGO=django==1.4.13
  - DJANGO=django==1.5
  - DJANGO=django==1.6
  - DJANGO=https://www.djangoproject.com/download/1.7c1/tarball/
# Django 1.4 doesn't support Python 3
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=https://www.djangoproject.com/download/1.7c1/tarball/
    - python: "3.3"
      env: DJANGO=django==1.4.13
    - python: "3.4"
      env: DJANGO=django==1.4.13
# command to install dependencies
# unittest2 should be only installed for python 2.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install $DJANGO
# command to run tests
script: python setup.py test